_target_: pytorch_lightning.Trainer
gpus: 1
log_every_n_steps: 12
callbacks:
- _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${general.monitor}
  patience: 5
- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${general.monitor}
  save_top_k: 1